<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net9.0;net48</TargetFrameworks>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	<LangVersion>latest</LangVersion>
	</PropertyGroup>
	
  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.3.0" />
    <PackageReference Include="Syncfusion.Licensing" Version="30.1.37" />
  </ItemGroup>

  <!-- Syncfusion packages for PDF conversion -->
  <ItemGroup Condition="'$(TargetFramework)' == 'net9.0'">
    <PackageReference Include="Syncfusion.XlsIORenderer.NET" Version="30.1.37" />
    <PackageReference Include="Syncfusion.PresentationRenderer.NET" Version="30.1.37" />
    <PackageReference Include="Syncfusion.Pdf.NET" Version="30.1.37" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net48'">
    <PackageReference Include="Syncfusion.ExcelToPdfConverter.AspNet.Mvc5" Version="30.1.37" />
    <PackageReference Include="Syncfusion.OfficeChartToImageConverter.AspNet.Mvc5" Version="30.1.37" />
    <PackageReference Include="Syncfusion.PresentationToPdfConverter.AspNet.Mvc5" Version="30.1.37" />
    <PackageReference Include="Syncfusion.Pdf.AspNet.Mvc5" Version="30.1.37" />
  </ItemGroup>

</Project>
